export const SuccessMsg = {
  SERVER_RUNNING: 'Server started successfully on ',
  DATABASE_CONNECTED: 'Database connected successfully ✅',
  REDIS_CONNECTED: 'Redis connected successfully 🎉',
  CACHE_CONNECTED: 'Cache service connected successfully',
  AUTH_SUCCESS: 'User authenticated successfully',
  OTP_SENT: 'OTP sent successfully',
  PASSWORD_CHANGED: 'Password updated successfully',
  USER_REGISTERED: 'User registered successfully',
  USER_LOGGED_IN: 'User logged in successfully',
  TOKEN_REFRESHED: 'Access token refreshed successfully',
  PAYMENT_SUCCESS: 'Payment processed successfully',
  TRANSACTION_COMPLETED: 'Transaction completed successfully',
  FILE_UPLOADED: 'File uploaded successfully',
  EMAIL_SENT: 'Email sent successfully',
  PUSH_NOTIFICATION_SENT: 'Push notification sent successfully',
  DATA_SAVED: 'Data saved successfully',
  DATA_UPDATED: 'Data updated successfully',
  DATA_DELETED: 'Data deleted successfully',
  QUERY_EXECUTED: 'Database query executed successfully',
  CACHE_CLEARED: 'Cache cleared successfully',
  SESSION_EXPIRED: 'Session expired successfully',
  LOGOUT_SUCCESS: 'User logged out successfully',
  CONFIG_LOADED: 'Configuration loaded successfully',
  API_REQUEST_SUCCESS: 'API request processed successfully',
  JOB_EXECUTED: 'Scheduled job executed successfully',
  WEBHOOK_TRIGGERED: 'Webhook triggered successfully',
  THIRD_PARTY_SERVICE_CONNECTED: 'Third-party service connected successfully',
  IMAGE_PROCESSED: 'Image processed successfully',
  REPORT_GENERATED: 'Report generated successfully',
  STATUS_UPDATED: 'Status updated successfully',
  MOVIE_UPDATED: 'Movie updated successfully',
  MOVIE_STATUS_UPDATED: 'Movie status updated successfully',
  MOVIE_DELETED: 'Movie deleted successfully',
  MOVIE_ADDED: 'Movie added successfully',
  THEATER_UPDATED: 'Theater Updated Successfully',  
};
