const ERROR_MESSAGES = {
  AUTHENTICATION: {
    UNAUTHORIZED: 'Unauthorized access.',
    INVALID_REFRESH_TOKEN: 'Invalid or expired refresh token.',
    TOKEN_EXPIRED: 'Authentication token expired.',
    TOKEN_MISSING: 'Authentication token missing.',
    INVALID_CREDENTIALS: 'Invalid login credentials.',
    SESSION_EXPIRED: 'Session has expired, please log in again.',
    ACCOUNT_LOCKED: 'Account has been locked due to multiple failed login attempts.',
    PERMISSION_DENIED: 'You do not have permission to perform this action.',
    GOOGLE_AUTH_FAILED: 'Google Authentication Failed',
    FACEBOOK_AUTH_FAILED: 'Facebook Authentication Failed',
    USER_NOT_FOUND: 'User Not Found!',
    INVALID_ACCESS_TOKEN: 'Invalid Acess Token!',
    BLOCKED_USER: 'Your Blocked By admin',
    ADMIN_BLOCKED: 'Your account admin register your not have access',
    YOUR_NOT_ADMIN: 'Your do not have admin access!',
    APPLICATION_UNDER_PROCESS: 'Your application is still being processed.',
  },
  VALIDATION: {
    BAD_REQUEST: 'Invalid request format.',
    MISSING_REQUIRED_FIELDS: 'Required fields are missing.',
    INVALID_INPUT: 'Invalid input data.',
    PASSWORD_TOO_WEAK: 'Password does not meet security requirements.',
    EMAIL_ALREADY_EXISTS: 'Email already registered.',
    EMAIL_FORMAT_INVALID: 'Invalid email format.',
    PHONE_NUMBER_INVALID: 'Invalid phone number format.',
    DATE_FORMAT_INVALID: 'Invalid date format.',
    PASSWORD_MISMATCH: 'Passwords do not match.',
    EMPTY_EMAIL_OTP: 'Empty Email or OTP, Please try again!',
    INVALID_OTP: 'Invalid OTP, Please try again!',
    USER_ALREADY_EXISTS: 'User already exists!',
  },
  DATABASE: {
    CONNECTION_FAILED: 'Database connection failed.',
    DUPLICATE_ENTRY: 'Duplicate entry detected.',
    RESOURCE_NOT_FOUND: 'Requested resource not found.',
    QUERY_FAILED: 'Database query execution failed.',
    TRANSACTION_FAILED: 'Database transaction failed.',
    RECORD_NOT_SAVED: 'Failed to save record to the database.',
    FAILED_STORING_OTP: 'Failed to store OTP in Redis.',
  },
  RATE_LIMITING: {
    TOO_MANY_REQUESTS: 'Too many requests, slow down!',
    SERVICE_UNAVAILABLE: 'Service temporarily unavailable.',
    API_LIMIT_REACHED: 'API rate limit reached, try again later.',
  },
  NETWORK: {
    NETWORK_ERROR: 'Network connection error.',
    TIMEOUT_ERROR: 'Network request timed out.',
    SERVICE_NOT_REACHABLE: 'Service is not reachable at the moment.',
    DNS_LOOKUP_FAILED: 'DNS lookup failed.',
  },
  GENERAL: {
    INTERNAL_SERVER_ERROR: 'Internal server error.',
    REQUEST_TIMEOUT: 'Request timed out, please try again.',
    METHOD_NOT_ALLOWED: 'HTTP method not allowed for this endpoint.',
    OPERATION_NOT_SUPPORTED: 'Requested operation is not supported.',
    FEATURE_NOT_AVAILABLE: 'Feature is not available at this time.',
    INVALID_QUERY_PARAMS: 'Invalid query parameters.',
    REDIS_CONNECTION_ERROR: 'Redis connection failed:',
    FAILED_SENDING_OTP: 'Failed to send OTP email.',
    FAILED_FETCHING_THEATERS: 'Failed to fetch theaters data'
  },
  SECURITY: {
    ACCESS_DENIED: 'Access denied due to security restrictions.',
    XSS_DETECTED: 'Potential cross-site scripting (XSS) attack detected.',
    CSRF_TOKEN_INVALID: 'CSRF token validation failed.',
    ENCRYPTION_ERROR: 'Error in encrypting or decrypting data.',
  },
  FILE_UPLOAD: {
    INVALID_FILE_FORMAT: 'Uploaded file format is not supported.',
    FILE_TOO_LARGE: 'Uploaded file exceeds size limit.',
    FILE_NOT_FOUND: 'Uploaded file could not be found.',
    UNSUPPORTED_FILE_TYPE: 'File type is not supported.',
  },
  THIRD_PARTY: {
    PAYMENT_FAILURE: 'Payment processing failed.',
    SMS_SERVICE_ERROR: 'SMS service encountered an error.',
    EMAIL_SERVICE_ERROR: 'Email service unavailable.',
    EXTERNAL_API_ERROR: 'External API request failed.',
    WEBHOOK_ERROR: 'Webhook processing failed.',
  },
};

export default ERROR_MESSAGES;
